import os
import smtplib
import pandas as pd

from email.message import EmailMessage
from dotenv import load_dotenv


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()


# ============================================================
# GMAIL SETTINGS
# ============================================================

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


# ============================================================
# SEND JOB EMAIL
# ============================================================

def send_job_email(jobs):

    # --------------------------------------------------------
    # ACCEPT BOTH DATAFRAME AND LIST
    # --------------------------------------------------------

    if jobs is None:
        return False

    if isinstance(jobs, pd.DataFrame):

        if jobs.empty:
            return False

        df = jobs.copy()

    elif isinstance(jobs, list):

        if len(jobs) == 0:
            return False

        df = pd.DataFrame(jobs)

    else:

        try:
            df = pd.DataFrame(jobs)

        except Exception:
            return False

    # --------------------------------------------------------
    # CHECK DATAFRAME
    # --------------------------------------------------------

    if df.empty:
        return False

    # --------------------------------------------------------
    # EMAIL CONFIGURATION
    # --------------------------------------------------------

    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    if not sender:
        raise ValueError(
            "EMAIL_SENDER is missing from .env"
        )

    if not password:
        raise ValueError(
            "EMAIL_PASSWORD is missing from .env"
        )

    if not receiver:
        raise ValueError(
            "EMAIL_RECEIVER is missing from .env"
        )

    # --------------------------------------------------------
    # CREATE EMAIL
    # --------------------------------------------------------

    message = EmailMessage()

    message["Subject"] = (
        f"🚀 CareerPilot AI - "
        f"{len(df)} Matching Job Opportunities"
    )

    message["From"] = sender
    message["To"] = receiver

    # --------------------------------------------------------
    # EMAIL BODY
    # --------------------------------------------------------

    body = []

    body.append(
        "CareerPilot AI found matching job opportunities "
        "for you.\n\n"
    )

    body.append(
        "=" * 60 + "\n\n"
    )

    for index, (_, job) in enumerate(
        df.iterrows(),
        start=1
    ):

        title = str(
            job.get(
                "title",
                "Job Opportunity"
            )
        )

        company = str(
            job.get(
                "company",
                "Company not specified"
            )
        )

        location = str(
            job.get(
                "location",
                "Location not specified"
            )
        )

        score = job.get(
            "score",
            "N/A"
        )

        url = str(
            job.get(
                "url",
                ""
            )
        )

        body.append(
            f"{index}. {title}\n"
        )

        body.append(
            f"🏢 Company: {company}\n"
        )

        body.append(
            f"📍 Location: {location}\n"
        )

        body.append(
            f"🎯 Match Score: {score}%\n"
        )

        if url.startswith("http"):

            body.append(
                f"🔗 Apply: {url}\n"
            )

        body.append(
            "\n" + "-" * 60 + "\n\n"
        )

    body.append(
        "Generated by CareerPilot AI 🚀"
    )

    message.set_content(
        "".join(body)
    )

    # --------------------------------------------------------
    # SEND THROUGH GMAIL
    # --------------------------------------------------------

    try:

        with smtplib.SMTP(
            SMTP_SERVER,
            SMTP_PORT
        ) as server:

            server.starttls()

            server.login(
                sender,
                password
            )

            server.send_message(
                message
            )

        print(
            f"✅ Email sent successfully to {receiver}"
        )

        return True

    except smtplib.SMTPAuthenticationError:

        print(
            "❌ Gmail authentication failed."
        )

        print(
            "Check your Gmail App Password."
        )

        return False

    except Exception as error:

        print(
            f"❌ Email sending failed: {error}"
        )

        return False